import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings._();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('uz'),
    Locale('tj'),
    Locale('ru'),
    Locale('en'),
  ];

  static String tr(String localeCode, String key) {
    return _texts[localeCode]?[key] ?? _texts['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _texts =
      <String, Map<String, String>>{
        'en': _en,
        'uz': _merge(_en, _uzOverrides),
        'tj': _merge(_en, _tjOverrides),
        'ru': _merge(_en, _ruOverrides),
      };

  static Map<String, String> _merge(
    Map<String, String> base,
    Map<String, String> overrides,
  ) {
    return <String, String>{...base, ...overrides};
  }

  static const Map<String, String> _en = <String, String>{
    'app_title': 'Smart Tasbeeh',
    'tab_tasbeh': 'Tasbeeh',
    'tab_zikrlar': 'Zikrs',
    'tab_qibla': 'Qibla',
    'tab_stats': 'Statistics',
    'tab_settings': 'Settings',
    'current_zikr': 'Current zikr',
    'count': 'Count',
    'target': 'Target',
    'set_target': 'Select target',
    'progress': 'Progress',
    'tap_hint': 'Tap: +1',
    'long_press_hint': 'Long press: fast counting',
    'undo': 'Undo (-1)',
    'reset': 'Reset',
    'save_session': 'Save session',
    'session_saved': 'Session saved',
    'session_auto_saved': 'Session auto-save is enabled',
    'reset_confirm_title': 'Reset counter?',
    'reset_confirm_body': 'Current zikr counter will be set to 0.',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'goal_reached_title': 'Target reached',
    'goal_reached_body': 'Congratulations! You reached your target.',
    'stats_today': 'Today',
    'stats_week': 'Weekly (7 days)',
    'stats_month': 'Monthly (30 days)',
    'stats_streak_title': 'Streak',
    'stats_days': 'days',
    'stats_total_all_time': 'All-time total',
    'stats_heatmap_title': 'Activity heatmap',
    'stats_distribution': 'Zikr distribution',
    'stats_low': 'Low',
    'stats_high': 'High',
    'most_used': 'Most used zikr',
    'no_data': 'No data',
    'theme': 'Theme',
    'theme_system': 'System',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'language': 'Language',
    'choose_lang': 'Choose language',
    'vibration': 'Vibration',
    'sound': 'Sound',
    'reminder_daily': 'Daily reminder',
    'reminder_friday': 'Friday reminder',
    'qibla_title': 'Qibla Direction',
    'qibla_desc':
        'Compass and geolocation integration is needed for live Qibla direction.',
    'qibla_placeholder': 'Qibla module is ready for integration.',
    'prayer_times': 'Prayer times',
    'nearby_mosques': 'Nearby mosques',
    'coming_soon': 'Coming soon',
    'mini_duas': 'Mini duas',
    'dua_of_day': 'Dua of the day',
    'before_sleep': 'Before sleep zikr',
    'after_prayer': 'After prayer zikr',
    'active': 'Active',
    'zikr_subhanallah': 'Subhanallah',
    'zikr_alhamdulillah': 'Alhamdulillah',
    'zikr_allahuakbar': 'Allahu Akbar',
    'zikr_astaghfirullah': 'Astaghfirullah',
    'target_sheet_title': 'Update target',
    'target_sheet_subtitle': 'Choose a target value',
    'language_sheet_title': 'Choose language',
    'direction_label': 'Direction',
    'distance_label': 'Distance',
    'stats_last_7_days': 'Last 7 days',
    'stats_weekly_chart': 'Weekly chart',
    'settings_general_section': 'General',
    'settings_feedback_section': 'Sound & vibration',
    'settings_reminders_section': 'Reminders',
    'settings_theme_subtitle': 'System, light or dark mode',
    'settings_language_subtitle': 'Application language',
    'settings_vibration_subtitle': 'Haptic feedback on count',
    'settings_sound_subtitle': 'System click on count',
    'settings_reminder_daily_subtitle': 'Daily zikr reminder',
    'settings_reminder_friday_subtitle': 'Friday reminder',
    'active_zikr_label': 'Active zikr',
  };

  static const Map<String, String> _uzOverrides = <String, String>{
    'tab_tasbeh': 'Tasbeh',
    'tab_zikrlar': 'Zikrlar',
    'tab_qibla': 'Qibla',
    'tab_stats': 'Statistika',
    'tab_settings': 'Sozlamalar',
    'current_zikr': 'Joriy zikr',
    'count': 'Sanoq',
    'target': 'Maqsad',
    'set_target': 'Maqsadni tanlang',
    'tap_hint': 'Bosish: +1',
    'long_press_hint': 'Uzoq bosish: tez sanash',
    'save_session': 'Sessiyani saqlash',
    'session_saved': 'Sessiya saqlandi',
    'session_auto_saved': 'Sessiya avtomatik saqlanadi',
    'reset_confirm_title': 'Sanoqni tiklash?',
    'reset_confirm_body': "Joriy zikr sanog'i 0 ga tushiriladi.",
    'cancel': 'Bekor qilish',
    'confirm': 'Tasdiqlash',
    'goal_reached_title': 'Maqsad bajarildi',
    'goal_reached_body': 'Tabriklaymiz! Maqsadga yetdingiz.',
    'stats_today': 'Bugun',
    'stats_week': 'Haftalik (7 kun)',
    'stats_month': 'Oylik (30 kun)',
    'stats_streak_title': 'Ketma-ket',
    'stats_days': 'kun',
    'stats_total_all_time': 'Jami',
    'stats_heatmap_title': 'Faollik xaritasi',
    'stats_distribution': 'Zikr taqsimoti',
    'stats_low': 'Kam',
    'stats_high': 'Ko\'p',
    'most_used': "Eng ko'p ishlatilgan zikr",
    'no_data': "Ma'lumot yo'q",
    'theme': 'Mavzu',
    'theme_system': "Tizim bo'yicha",
    'theme_light': 'Kunduzgi',
    'theme_dark': 'Tungi',
    'language': 'Til',
    'choose_lang': 'Tilni tanlang',
    'vibration': 'Vibratsiya',
    'sound': 'Ovoz',
    'reminder_daily': 'Kunlik eslatma',
    'reminder_friday': 'Juma eslatmasi',
    'qibla_title': "Qibla yo'nalishi",
    'qibla_placeholder': 'Qibla moduli integratsiyaga tayyor.',
    'prayer_times': 'Namoz vaqtlari',
    'nearby_mosques': 'Yaqin masjidlar',
    'coming_soon': 'Tez orada',
    'active': 'Faol',
    'zikr_subhanallah': 'Subhanalloh',
    'zikr_alhamdulillah': 'Alhamdulillah',
    'zikr_allahuakbar': 'Allohu Akbar',
    'zikr_astaghfirullah': "Astag'firulloh",
    'target_sheet_title': 'Maqsadni yangilang',
    'target_sheet_subtitle': 'Yangi maqsad qiymatini tanlang',
    'language_sheet_title': 'Tilni tanlang',
    'direction_label': 'Yo\'nalish',
    'distance_label': 'Masofa',
    'stats_weekly_chart': 'Haftalik grafik',
    'settings_general_section': 'Umumiy',
    'settings_feedback_section': 'Ovoz va vibratsiya',
    'settings_reminders_section': 'Eslatmalar',
    'settings_theme_subtitle': 'Tizim, kunduzgi yoki tungi mavzu',
    'settings_language_subtitle': 'Ilova interfeysi tili',
    'settings_vibration_subtitle': 'Bosishda haptic feedback',
    'settings_sound_subtitle': 'Bosishda system click ovozi',
    'settings_reminder_daily_subtitle': 'Har kuni zikrga eslatma',
    'settings_reminder_friday_subtitle': 'Juma kuni maxsus eslatma',
    'active_zikr_label': 'Faol zikr',
  };

  static const Map<String, String> _tjOverrides = <String, String>{
    'tab_tasbeh': 'Тасбеҳ',
    'tab_zikrlar': 'Зикрҳо',
    'tab_qibla': 'Қибла',
    'tab_stats': 'Омор',
    'tab_settings': 'Танзимот',
    'current_zikr': 'Зикри ҷорӣ',
    'count': 'Шумора',
    'target': 'Ҳадаф',
    'theme': 'Намуд',
    'language': 'Забон',
    'choose_lang': 'Забонро интихоб кунед',
    'vibration': 'Вибратсия',
    'sound': 'Овоз',
    'reminder_daily': 'Ёдрасии рӯзона',
    'reminder_friday': 'Ёдрасии ҷумъа',
    'qibla_title': 'Самти Қибла',
    'coming_soon': 'Ба наздикӣ',
    'active': 'Фаъол',
    'zikr_subhanallah': 'Субҳоналлоҳ',
    'zikr_alhamdulillah': 'Алҳамдулиллоҳ',
    'zikr_allahuakbar': 'Аллоҳу Акбар',
    'zikr_astaghfirullah': 'Астағфируллоҳ',
  };

  static const Map<String, String> _ruOverrides = <String, String>{
    'tab_tasbeh': 'Тасбих',
    'tab_zikrlar': 'Зикры',
    'tab_qibla': 'Кибла',
    'tab_stats': 'Статистика',
    'tab_settings': 'Настройки',
    'current_zikr': 'Текущий зикр',
    'count': 'Счет',
    'target': 'Цель',
    'theme': 'Тема',
    'language': 'Язык',
    'choose_lang': 'Выберите язык',
    'vibration': 'Вибрация',
    'sound': 'Звук',
    'reminder_daily': 'Ежедневное напоминание',
    'reminder_friday': 'Напоминание в пятницу',
    'qibla_title': 'Направление Киблы',
    'coming_soon': 'Скоро',
    'active': 'Активно',
    'zikr_subhanallah': 'Субханаллах',
    'zikr_alhamdulillah': 'Альхамдулиллях',
    'zikr_allahuakbar': 'Аллаху Акбар',
    'zikr_astaghfirullah': 'Астагфируллах',
  };
}
