import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings._();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('uz'),
    Locale('tj'),
    Locale('ru'),
    Locale('en'),
  ];

  static String tr(String localeCode, String key) {
    return _texts[localeCode]?[key] ?? _texts['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>>
  _texts = <String, Map<String, String>>{
    'uz': <String, String>{
      'app_title': 'Smart Tasbeeh',
      'tab_tasbeh': 'Tasbeh',
      'tab_zikrlar': 'Zikrlar',
      'tab_qibla': 'Qibla',
      'tab_stats': 'Statistika',
      'tab_settings': 'Sozlamalar',
      'current_zikr': 'Joriy zikr',
      'count': 'Sanoq',
      'target': 'Maqsad',
      'set_target': 'Maqsadni tanlang',
      'progress': 'Progress',
      'tap_hint': 'Bosish: +1',
      'long_press_hint': 'Uzoq bosish: tez sanash',
      'undo': 'Undo (-1)',
      'reset': 'Reset',
      'save_session': 'Sessiyani saqlash',
      'session_saved': 'Sessiya saqlandi',
      'session_auto_saved': 'Sessiya avtomatik saqlanadi',
      'reset_confirm_title': 'Sanoqni tiklash?',
      'reset_confirm_body': "Joriy zikr sanog'i 0 ga tushiriladi.",
      'cancel': 'Bekor qilish',
      'confirm': 'Tasdiqlash',
      'goal_reached_title': 'Maqsad bajarildi',
      'goal_reached_body': 'Tabriklaymiz! Maqsadga yetdingiz.',
      'stats_today': 'Bugun',
      'stats_week': 'Haftalik (7 kun)',
      'stats_month': 'Oylik (30 kun)',
      'most_used': "Eng ko'p ishlatilgan zikr",
      'no_data': "Ma'lumot yo'q",
      'theme': 'Mavzu',
      'theme_system': "Tizim bo'yicha",
      'theme_light': 'Kunduzgi',
      'theme_dark': 'Tungi',
      'language': 'Til',
      'choose_lang': 'Tilni tanlang',
      'vibration': 'Vibratsiya',
      'sound': 'Ovoz',
      'reminder_daily': 'Kunlik eslatma',
      'reminder_friday': 'Juma eslatmasi',
      'qibla_title': "Qibla yo'nalishi",
      'qibla_desc':
          "Kompas va joylashuv asosidagi Qibla funksiyasi uchun sensor va joylashuv integratsiyasi kerak.",
      'qibla_placeholder': 'Qibla moduli integratsiyaga tayyor.',
      'prayer_times': 'Namoz vaqtlari',
      'nearby_mosques': 'Yaqin masjidlar',
      'coming_soon': 'Tez orada',
      'mini_duas': 'Mini duolar',
      'dua_of_day': 'Kun duosi',
      'before_sleep': 'Uyqudan oldin zikr',
      'after_prayer': 'Namozdan keyingi zikr',
      'active': 'Faol',
      'zikr_subhanallah': 'Subhanalloh',
      'zikr_alhamdulillah': 'Alhamdulillah',
      'zikr_allahuakbar': 'Allohu Akbar',
      'zikr_astaghfirullah': "Astag'firulloh",
    },
    'tj': <String, String>{
      'app_title': 'Smart Tasbeeh',
      'tab_tasbeh': 'Тасбеҳ',
      'tab_zikrlar': 'Зикрҳо',
      'tab_qibla': 'Қибла',
      'tab_stats': 'Омор',
      'tab_settings': 'Танзимот',
      'current_zikr': 'Зикри ҷорӣ',
      'count': 'Шумора',
      'target': 'Ҳадаф',
      'set_target': 'Ҳадафро интихоб кунед',
      'progress': 'Пешрафт',
      'tap_hint': 'Ламс: +1',
      'long_press_hint': 'Пахши дароз: ҳисоби тез',
      'undo': 'Бозгашт (-1)',
      'reset': 'Аз нав',
      'save_session': 'Нигоҳдории сессия',
      'session_saved': 'Сессия нигоҳ дошта шуд',
      'session_auto_saved': 'Сессия худкор нигоҳ дошта мешавад',
      'reset_confirm_title': 'Шумора аз нав шавад?',
      'reset_confirm_body': 'Шумораи зикри ҷорӣ ба 0 мефарояд.',
      'cancel': 'Бекор',
      'confirm': 'Тасдиқ',
      'goal_reached_title': 'Ҳадаф иҷро шуд',
      'goal_reached_body': 'Табрик! Шумо ба ҳадаф расидед.',
      'stats_today': 'Имрӯз',
      'stats_week': 'Ҳафта (7 рӯз)',
      'stats_month': 'Моҳ (30 рӯз)',
      'most_used': 'Зикри бештар истифодашуда',
      'no_data': 'Маълумот нест',
      'theme': 'Намуд',
      'theme_system': 'Мувофиқи система',
      'theme_light': 'Равшан',
      'theme_dark': 'Торик',
      'language': 'Забон',
      'choose_lang': 'Забонро интихоб кунед',
      'vibration': 'Вибратсия',
      'sound': 'Овоз',
      'reminder_daily': 'Ёдрасии рӯзона',
      'reminder_friday': 'Ёдрасии ҷумъа',
      'qibla_title': 'Самти Қибла',
      'qibla_desc':
          'Барои самти Қибла ҳамгироии қутбнамо ва ҷойгиршавӣ лозим аст.',
      'qibla_placeholder': 'Модули Қибла барои ҳамгироӣ омода аст.',
      'prayer_times': 'Вақтҳои намоз',
      'nearby_mosques': 'Масҷидҳои наздик',
      'coming_soon': 'Ба наздикӣ',
      'mini_duas': 'Дуоҳои хурд',
      'dua_of_day': 'Дуои рӯз',
      'before_sleep': 'Зикр пеш аз хоб',
      'after_prayer': 'Зикр баъди намоз',
      'active': 'Фаъол',
      'zikr_subhanallah': 'Субҳоналлоҳ',
      'zikr_alhamdulillah': 'Алҳамдулиллоҳ',
      'zikr_allahuakbar': 'Аллоҳу Акбар',
      'zikr_astaghfirullah': 'Астағфируллоҳ',
    },
    'ru': <String, String>{
      'app_title': 'Smart Tasbeeh',
      'tab_tasbeh': 'Тасбих',
      'tab_zikrlar': 'Зикры',
      'tab_qibla': 'Кибла',
      'tab_stats': 'Статистика',
      'tab_settings': 'Настройки',
      'current_zikr': 'Текущий зикр',
      'count': 'Счет',
      'target': 'Цель',
      'set_target': 'Выберите цель',
      'progress': 'Прогресс',
      'tap_hint': 'Нажатие: +1',
      'long_press_hint': 'Долгое нажатие: быстрый счет',
      'undo': 'Отмена (-1)',
      'reset': 'Сброс',
      'save_session': 'Сохранить сессию',
      'session_saved': 'Сессия сохранена',
      'session_auto_saved': 'Сессия сохраняется автоматически',
      'reset_confirm_title': 'Сбросить счет?',
      'reset_confirm_body': 'Счет текущего зикра будет обнулен.',
      'cancel': 'Отмена',
      'confirm': 'Подтвердить',
      'goal_reached_title': 'Цель достигнута',
      'goal_reached_body': 'Поздравляем! Цель выполнена.',
      'stats_today': 'Сегодня',
      'stats_week': 'Неделя (7 дней)',
      'stats_month': 'Месяц (30 дней)',
      'most_used': 'Самый используемый зикр',
      'no_data': 'Нет данных',
      'theme': 'Тема',
      'theme_system': 'Системная',
      'theme_light': 'Светлая',
      'theme_dark': 'Темная',
      'language': 'Язык',
      'choose_lang': 'Выберите язык',
      'vibration': 'Вибрация',
      'sound': 'Звук',
      'reminder_daily': 'Ежедневное напоминание',
      'reminder_friday': 'Напоминание в пятницу',
      'qibla_title': 'Направление Киблы',
      'qibla_desc':
          'Для определения Киблы нужна интеграция компаса и геолокации.',
      'qibla_placeholder': 'Модуль Киблы готов к интеграции.',
      'prayer_times': 'Времена намаза',
      'nearby_mosques': 'Ближайшие мечети',
      'coming_soon': 'Скоро',
      'mini_duas': 'Мини-дуа',
      'dua_of_day': 'Дуа дня',
      'before_sleep': 'Зикр перед сном',
      'after_prayer': 'Зикр после намаза',
      'active': 'Активно',
      'zikr_subhanallah': 'Субханаллах',
      'zikr_alhamdulillah': 'Альхамдулиллях',
      'zikr_allahuakbar': 'Аллаху Акбар',
      'zikr_astaghfirullah': 'Астагфируллах',
    },
    'en': <String, String>{
      'app_title': 'Smart Tasbeeh',
      'tab_tasbeh': 'Tasbeeh',
      'tab_zikrlar': 'Zikrs',
      'tab_qibla': 'Qibla',
      'tab_stats': 'Statistics',
      'tab_settings': 'Settings',
      'current_zikr': 'Current zikr',
      'count': 'Count',
      'target': 'Target',
      'set_target': 'Select target',
      'progress': 'Progress',
      'tap_hint': 'Tap: +1',
      'long_press_hint': 'Long press: fast counting',
      'undo': 'Undo (-1)',
      'reset': 'Reset',
      'save_session': 'Save session',
      'session_saved': 'Session saved',
      'session_auto_saved': 'Session auto-save is enabled',
      'reset_confirm_title': 'Reset counter?',
      'reset_confirm_body': 'Current zikr counter will be set to 0.',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'goal_reached_title': 'Target reached',
      'goal_reached_body': 'Congratulations! You reached your target.',
      'stats_today': 'Today',
      'stats_week': 'Weekly (7 days)',
      'stats_month': 'Monthly (30 days)',
      'most_used': 'Most used zikr',
      'no_data': 'No data',
      'theme': 'Theme',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'language': 'Language',
      'choose_lang': 'Choose language',
      'vibration': 'Vibration',
      'sound': 'Sound',
      'reminder_daily': 'Daily reminder',
      'reminder_friday': 'Friday reminder',
      'qibla_title': 'Qibla Direction',
      'qibla_desc':
          'Compass and geolocation integration is needed for live Qibla direction.',
      'qibla_placeholder': 'Qibla module is ready for integration.',
      'prayer_times': 'Prayer times',
      'nearby_mosques': 'Nearby mosques',
      'coming_soon': 'Coming soon',
      'mini_duas': 'Mini duas',
      'dua_of_day': 'Dua of the day',
      'before_sleep': 'Before sleep zikr',
      'after_prayer': 'After prayer zikr',
      'active': 'Active',
      'zikr_subhanallah': 'Subhanallah',
      'zikr_alhamdulillah': 'Alhamdulillah',
      'zikr_allahuakbar': 'Allahu Akbar',
      'zikr_astaghfirullah': 'Astaghfirullah',
    },
  };
}
